### ISSUE TITLE
FATAL app unable to boot: Neoid 0.1.2 & Neography 0.9.10 (or master/HEAD)

### ISSUE THREAD

**Issue by pboling** [neoid-gem/neoid#23]
FYI: @maxdemarzi @elado 

I had neography as a git dependency in my gemfile.  When I updated it recently neoid stopped working.
## Compatible with Neoid
- maxdemarzi/neography@e0f56c3900f9ef8b0b0134efcdc0c39209343f03
- maxdemarzi/neography@f800179478a3b368314c194d22248308f9594448
- [neography v 1.0.9](https://rubygems.org/gems/neography/versions/1.0.9)
## **Not** Compatible with Neoid
- maxdemarzi/neography@aa6c1aedd2e6ce38b197f3b16e9020c645eb05be
- [neography v 1.0.10](https://rubygems.org/gems/neography/versions/1.0.10)

Using maxdemarzi/neography@aa6c1aedd2e6ce38b197f3b16e9020c645eb05be

```
neoid-0.1.2/lib/neoid/batch.rb:89:in `block in flush_batch': undefined method `collect' for #<String:0x00000006167c30> (NoMethodError)
```

Here's the longer trace:

```
2013-04-17T03:19:02.646896+00:00 app[web.1]: /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/batch.rb:89:in `block in flush_batch': undefined method `collect' for #<String:0x00000006167c30> (NoMethodError)
2013-04-17T03:19:02.646896+00:00 app[web.1]:    from /app/vendor/ruby-1.9.3/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
2013-04-17T03:19:02.646896+00:00 app[web.1]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/batch.rb:88:in `flush_batch'
2013-04-17T03:19:02.646896+00:00 app[web.1]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/batch.rb:76:in `run'
2013-04-17T03:19:02.646896+00:00 app[web.1]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid.rb:69:in `batch'
2013-04-17T03:19:02.646896+00:00 app[web.1]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid.rb:218:in `initialize_subrefs'
2013-04-17T03:19:02.646896+00:00 app[web.1]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid.rb:59:in `initialize_server'
2013-04-17T03:19:02.646896+00:00 app[web.1]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid.rb:54:in `initialize_all'
2013-04-17T03:19:02.646896+00:00 app[web.1]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/railtie.rb:7:in `block (2 levels) in <class:Railtie>'
```

Adding the specific ref to my gemfile fixed it:

```
gem 'neography', github: 'maxdemarzi/neography', ref: 'e0f56c3900f9ef8b0b0134efcdc0c39209343f03'
```

**Comment by pboling** [comment]
The 1.0.10 release is also not compatible with neoid but the stack trace changes to the below:

```
2013-06-17T20:12:56.646445+00:00 app[web.2]: /app/vendor/bundle/ruby/1.9.1/gems/neography-1.0.10/lib/neography/connection.rb:58:in `post_chunked': undefined method `>' for nil:NilClass (NoMethodError)
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neography-1.0.10/lib/neography/rest/batch.rb:35:in `batch'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neography-1.0.10/lib/neography/rest/batch.rb:14:in `execute'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neography-1.0.10/lib/neography/rest.rb:357:in `batch'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/batch.rb:89:in `block in flush_batch'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/ruby-1.9.3/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/batch.rb:88:in `flush_batch'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/batch.rb:76:in `run'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid.rb:69:in `batch'
2013-06-17T20:12:56.646445+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid.rb:218:in `initialize_subrefs'
2013-06-17T20:12:56.646638+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid.rb:59:in `initialize_server'
2013-06-17T20:12:56.646638+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid.rb:54:in `initialize_all'
2013-06-17T20:12:56.646638+00:00 app[web.2]:    from /app/vendor/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/railtie.rb:7:in `block (2 levels) in <class:Railtie>'
```

**Comment by pboling** [comment]
I don't know what's going on... I used to have trouble with this, but I don't anymore, 1.1.0 works.  maxdemarzi/neography/master HEAD works.
