### ISSUE TITLE
RuntimeError on neo_save(): "Accessed result too soon"

### ISSUE THREAD

**Issue by francoisbruneau** [neoid-gem/neoid#26]
When calling neo_save() on a model in a Resque asynchronous job, I frequently get this error:

```
RuntimeError
Accessed result too soon
/var/www/srv/webdoc/shared/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/batch.rb:149:in `result'
/var/www/srv/webdoc/shared/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/batch.rb:154:in `method_missing'
/var/www/srv/webdoc/shared/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/node.rb:127:in `_neo_save'
/var/www/srv/webdoc/shared/bundle/ruby/1.9.1/gems/neoid-0.1.2/lib/neoid/model_additions.rb:56:in `neo_save'
```

I can not reproduce this issue when synchronously saving the model using Rails console.

Any idea where it may come from?

**Comment by killinit** [comment]
I'am having same problem. Please help

**Comment by BenMorganIO** [comment]
Please go the http://github.com/BenMorganIO/neoid and submit the issue there. I'm trying to get this gem back up to date...

**Comment by killinit** [comment]
Sorry but I do not see issues tab on Your git.

**Comment by BenMorganIO** [comment]
Fixed!

**Comment by BenMorganIO** [comment]
For future reference: Issue explained with more [detail here](https://github.com/BenMorganIO/neoid/issues/1).
